apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        command: ["sh", "-c", "echo $VAULT_SECRET_USER && echo $VAULT_SECRET_PASSWORD && echo $USER_JfrogToken && echo $USER_ArgocdUsername && echo going to sleep... && sleep 10000"]
        env:
        - name: VAULT_SECRET_USER
          value: <path:ST0117/edge-config/data/secrets#username>
        - name: VAULT_SECRET_PASSWORD
          value: <path:ST0117/edge-config/data/secrets#password>
        - name:  USER_JfrogToken
          value: <path:gateway-config-v2/data/secrets#vaultGlobalArgocdUsername>
        - name: USER_ArgocdUsername
          value: <path:gateway-config-v2/data/secrets#vaultGlobalArgocdUsername>
