---
apiVersion: v1
kind: Secret
metadata:
  name: vtest-secret
type: Opaque
data:
  HTTPS_PROXY_DATA: <path:{{ .Values.edgeClusterConfig.storeId }}/edge-config/data/secrets#httpproxy>
  HTTP_PROXY_DATA: <path:{{ .Values.edgeClusterConfig.storeId }}/edge-config/data/secrets#httpsproxy> 
