---
apiVersion: v1
kind: Secret
metadata:
  name: vtest-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  HTTPS_PROXY_DATA: <path:{{ .Values.edgeClusterConfig.storeId }}/edge-config/data/secrets#nextgenProxy>
  HTTP_PROXY_DATA: <path:{{ .Values.edgeClusterConfig.storeId }}/edge-config/data/secrets#nextgenProxy> 
